project_name: "Gaussian_SLAM_kitti"
dataset_name: "kitti"
checkpoint_path: null
frame_limit: -1 # use first n frames. for debugging, set to -1 to disable
seed: 0
# data
input_path: null
output_path: output/KITTI/0
kitti_root: /home/shiladitya/Dataset/data_odometry_color/dataset/
raw_data_root: /home/shiladitya/Dataset/kitti_raw/
semkitti_root: /home/shiladitya/Dataset/SemanticKITTI/dataset/sequences
semkitti_config: third_party/semantic_kitti_api/config/semantic-kitti-all.yaml
seq_id: 0
# mapping
uniform_seed_interval: 3
iterations: 100
new_submap_iterations: 100
iou_thresh: 0.05
alpha_thre: 0.6
pruning_thre: 0
# tracking
gt_camera: True
track_iterations: 200
cam_rot_lr: 0.002
cam_trans_lr: 0.01
# cam
depth_scale: null
H: 376
W: 1241
fx: 718.856
fy: 718.856
cx: 607.1928
cy: 185.2157
crop_edge: 0
# distortion: [ 0.2624, -0.9531, -0.0054, 0.0026, 1.1633 ]